/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Community {
    #[serde(rename = "identifier")]
    pub identifier: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "discord_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub discord_url: Option<Option<String>>,
    #[serde(rename = "wiki_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wiki_url: Option<Option<String>>,
    #[serde(rename = "require_package_listing_approval", skip_serializing_if = "Option::is_none")]
    pub require_package_listing_approval: Option<bool>,
}

impl Community {
    pub fn new(identifier: String, name: String) -> Community {
        Community {
            identifier,
            name,
            discord_url: None,
            wiki_url: None,
            require_package_listing_approval: None,
        }
    }
}


