/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LegacyProfileCreateResponse {
    #[serde(rename = "key")]
    pub key: String,
}

impl LegacyProfileCreateResponse {
    pub fn new(key: String) -> LegacyProfileCreateResponse {
        LegacyProfileCreateResponse {
            key,
        }
    }
}


