/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarkdownResponse {
    #[serde(rename = "markdown", deserialize_with = "Option::deserialize")]
    pub markdown: Option<String>,
}

impl MarkdownResponse {
    pub fn new(markdown: Option<String>) -> MarkdownResponse {
        MarkdownResponse {
            markdown,
        }
    }
}


