/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OwLoginRequestBody {
    #[serde(rename = "jwt")]
    pub jwt: String,
}

impl OwLoginRequestBody {
    pub fn new(jwt: String) -> OwLoginRequestBody {
        OwLoginRequestBody {
            jwt,
        }
    }
}


