/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackageVersionMetrics {
    #[serde(rename = "downloads")]
    pub downloads: i32,
}

impl PackageVersionMetrics {
    pub fn new(downloads: i32) -> PackageVersionMetrics {
        PackageVersionMetrics {
            downloads,
        }
    }
}


