/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackageMetrics {
    #[serde(rename = "downloads")]
    pub downloads: i32,
    #[serde(rename = "rating_score")]
    pub rating_score: i32,
    #[serde(rename = "latest_version")]
    pub latest_version: String,
}

impl PackageMetrics {
    pub fn new(downloads: i32, rating_score: i32, latest_version: String) -> PackageMetrics {
        PackageMetrics {
            downloads,
            rating_score,
            latest_version,
        }
    }
}


