/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackageIndexEntry {
    #[serde(rename = "namespace")]
    pub namespace: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "version_number")]
    pub version_number: String,
    #[serde(rename = "file_format")]
    pub file_format: String,
    #[serde(rename = "file_size")]
    pub file_size: i32,
    #[serde(rename = "dependencies", skip_serializing_if = "Option::is_none")]
    pub dependencies: Option<String>,
}

impl PackageIndexEntry {
    pub fn new(namespace: String, name: String, version_number: String, file_format: String, file_size: i32) -> PackageIndexEntry {
        PackageIndexEntry {
            namespace,
            name,
            version_number,
            file_format,
            file_size,
            dependencies: None,
        }
    }
}


