/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackageListingRejectRequest {
    #[serde(rename = "rejection_reason")]
    pub rejection_reason: String,
    #[serde(rename = "internal_notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub internal_notes: Option<Option<String>>,
}

impl PackageListingRejectRequest {
    pub fn new(rejection_reason: String) -> PackageListingRejectRequest {
        PackageListingRejectRequest {
            rejection_reason,
            internal_notes: None,
        }
    }
}


