/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackageSubmissionStatus {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "form_errors", skip_serializing_if = "Option::is_none")]
    pub form_errors: Option<serde_json::Value>,
    #[serde(rename = "task_error")]
    pub task_error: bool,
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
}

impl PackageSubmissionStatus {
    pub fn new(id: String, status: String, task_error: bool) -> PackageSubmissionStatus {
        PackageSubmissionStatus {
            id,
            status,
            form_errors: None: None,
            task_error,
            result: None,
        }
    }
}


