/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackageListingUpdateResponse {
    #[serde(rename = "categories")]
    pub categories: Vec<crate::models::PackageCategoryExperimental>,
}

impl PackageListingUpdateResponse {
    pub fn new(categories: Vec<crate::models::PackageCategoryExperimental>) -> PackageListingUpdateResponse {
        PackageListingUpdateResponse {
            categories,
        }
    }
}


