/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SchemaChannelUpdateResponse {
    #[serde(rename = "channel_identifier")]
    pub channel_identifier: String,
    #[serde(rename = "checksum_sha256")]
    pub checksum_sha256: String,
}

impl SchemaChannelUpdateResponse {
    pub fn new(channel_identifier: String, checksum_sha256: String) -> SchemaChannelUpdateResponse {
        SchemaChannelUpdateResponse {
            channel_identifier,
            checksum_sha256,
        }
    }
}


