/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SocialAuthConnection {
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "avatar")]
    pub avatar: String,
}

impl SocialAuthConnection {
    pub fn new(provider: String, username: String, avatar: String) -> SocialAuthConnection {
        SocialAuthConnection {
            provider,
            username,
            avatar,
        }
    }
}


