/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserTeam {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "role")]
    pub role: String,
    #[serde(rename = "member_count")]
    pub member_count: i32,
}

impl UserTeam {
    pub fn new(name: String, role: String, member_count: i32) -> UserTeam {
        UserTeam {
            name,
            role,
            member_count,
        }
    }
}


