/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WikiPageUpsert {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "markdown_content")]
    pub markdown_content: String,
}

impl WikiPageUpsert {
    pub fn new(title: String, markdown_content: String) -> WikiPageUpsert {
        WikiPageUpsert {
            id: None,
            title,
            markdown_content,
        }
    }
}


