/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WikiPageDelete {
    #[serde(rename = "id")]
    pub id: String,
}

impl WikiPageDelete {
    pub fn new(id: String) -> WikiPageDelete {
        WikiPageDelete {
            id,
        }
    }
}


