/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WikiPage {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "datetime_created")]
    pub datetime_created: String,
    #[serde(rename = "datetime_updated")]
    pub datetime_updated: String,
    #[serde(rename = "markdown_content")]
    pub markdown_content: String,
}

impl WikiPage {
    pub fn new(id: String, title: String, slug: String, datetime_created: String, datetime_updated: String, markdown_content: String) -> WikiPage {
        WikiPage {
            id,
            title,
            slug,
            datetime_created,
            datetime_updated,
            markdown_content,
        }
    }
}


